### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by dm-aq** [xabgesagtx/telegram-spring-boot-starter-example#1]
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T19:41:47+03:00)
Maven home: /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building telegram-spring-boot-starter-example 0.17-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ telegram-spring-boot-starter-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ telegram-spring-boot-starter-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ telegram-spring-boot-starter-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/dm_aq/IdeaProjects/telegram-spring-boot-starter-example/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ telegram-spring-boot-starter-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ telegram-spring-boot-starter-example ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ telegram-spring-boot-starter-example ---
[INFO] Building jar: /Users/dm_aq/IdeaProjects/telegram-spring-boot-starter-example/target/telegram-spring-boot-starter-example-0.17-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.0.0.RELEASE:repackage (default) @ telegram-spring-boot-starter-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.717 s
[INFO] Finished at: 2018-04-14T16:15:08+03:00
[INFO] Final Memory: 23M/227M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:repackage (default) on project telegram-spring-boot-starter-example: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:repackage failed: A required class was missing while executing org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:repackage: org/springframework/core/io/support/SpringFactoriesLoader
[ERROR] -----------------------------------------------------

**Comment by dm-aq** [comment]
It can be fixed by changing version of spring-boot-starter-parent. 
The correct version: 2.0.1.RELEASE

**Comment by xabgesagtx** [comment]
Actually, I'm not sure why your build fails. The travis-ci build is not failing and it does not fail on my linux machine.

But I wanted to update the starter to spring boot 2.0.1.RELEASE anyway.

The new release 0.17 includes an update to spring boot 2.0.1.RELEASE.
